server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para o backend Spring Boot
    location /api/ {
        proxy_pass http://backend:8082;   # nome do serviço no docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
