services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meat_frontend
    ports:
      - "3000:80" # Mapeando a porta 80 do container para 3000 no host
    networks:
      - local-network

networks:
  default:
    name: local-network
    external: true
